### ISSUE TITLE
pv: command not found

### ISSUE THREAD

**Issue by TheBarzFR** [Zer0CoolX/guacamole-install-rhel#35]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. You have read the wiki and followed its guidelines, especially the [Installation Assumptions](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/Installation-Assumptions) page? Y
3. You have checked the wiki and existing issues for the same problem? Y
4. You are sure this issue is not specific to you personally and would affect others under similar circumstances? Y

**Describe the bug**
pv: command not found

Thanks for using MariaDB!
./guac-install.sh: line 1194: pv: command not found
./guac-install.sh: line 1204: pv: command not found
./guac-install.sh: line 1209: pv: command not found
./guac-install.sh: line 1234: pv: command not found

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /var/lib/tomcat/webapps/.keystore -destkeystore /var/lib/tomcat/webapps/.keystore -deststoretype pkcs12".
./guac-install.sh: line 1239: pv: command not found

**Environment (please complete the following information):**
 - CentOS 7.15

**Guacamole Options Selected**
 - Extensions: LDAP
 - Self-signed cert

**Comment by TheBarzFR** [comment]
You have specifiy to install PV requirement : 
# yum install  pv --enablerepo=epel

**Comment by Zer0CoolX** [comment]
Just to clarify, the script does install pv from epel (and obviously installs/enables epel). This can be seen on line ~957 of the script (for EPEL) and line ~1021 (for pv).

I have seen some rare cases, mirrors/repos with temporary issues can cause this behavior. Essentially enabling a given repo or downloading a given package fails causing errors like this later in the script. This could be caused by a mirror having connectivity issues, an expired SSL certs, etc. Often the best fix is to re-run the script and/or manually check the source is up/online.

Glad to see you got it worked out in your case.
