### ISSUE TITLE
[BUG] Blank Login Screen. /var/log/messages shows Unrecognized Timezone entry

### ISSUE THREAD

**Issue by CyberCam1969** [Zer0CoolX/guacamole-install-rhel#38]
Hey Zer0CoolX,

I'm the one on Reddit that has the blank screen on the login page issue. I have a full 12 minute video detailing the entire install (which has been sped up where it needs to be). At the end of the video you will see the output of the guacamole.properties and the tail -f /var/log/messages.

Here is the link to the video, which has a password, I will send you the password via pm on Reddit:
https://sfs.kiasystems.com/f/c8c9db8d547a4ccc8ed2/

**Comment by Zer0CoolX** [comment]
Thank you, I will review this asap. For anyone else reading this, read 3) under [Common Mistakes](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/Known-Issues-and-Common-Mistakes#common-mistakes) to see known causes of this problem.

**Comment by Zer0CoolX** [comment]
It appears the problem is likely related to issues between MySQL Connector J version 8.x and MariaDB versions provided by CentOS. There are 2 general solutions:

1. Change the variable for the connector version to a valid 5.x version. The variable: MYSQL_CON_VER="8.0.15" to something like MYSQL_CON_VER="5.1.47". 
2. Change the timezone in mariaDB by adding a line to the /etc/my.cnf file in the [mysqld] section. Add a line `default-time-zone='-04:00'` (replacing `-04:00` with whatever best fits your need in the format of `+/-00:00`).

See [Common Mistakes](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/Known-Issues-and-Common-Mistakes#common-mistakes) for more details under 3 and the bullet point. For anyone reading this, its specific to when the login screen is blank despite the script finishing properly AND the `tail -f /var/log/messages` command showing an JBDC error stating something like "The server timezone value x is unrecognized or represents more than one timezone".

I may revert the default MYSWL_CON_VER to 5.x until the problem between MySQL Connector 8.x and mariaDB in CentOS resolve the issues. 8.x was working until daylight savings time was in effect. I presumed the matter had already been fixed.

**Comment by CyberCam1969** [comment]
Thanks for the response, I will retest with your suggestions when I get home.

**Comment by CyberCam1969** [comment]
Great job with the fix... I can confirm that the second fix (editing the /etc/my.cnf file) works! You can close this issue at your leisure!

**Comment by Zer0CoolX** [comment]
For others sake, I have found that an existing install using MySQL Connector 8.x, LDAP auth and Lets Encrypt with a public domain continued to work properly even after day light savings changed. The MySQL Connector/mariaDB issue may only apply when using only mariaDB for auth.

Others should feel free to try 8.x in testing and confirm it works completely before attempting using 8.x in production. For now the script will use 5.x by default.
