### ISSUE TITLE
[BUG] Compiling Guacamole Client Fails from Git as Source

### ISSUE THREAD

**Issue by brianandcamera** [Zer0CoolX/guacamole-install-rhel#48]
Using the latest version from git, this happens on a fresh centos 7 install:

![image](https://user-images.githubusercontent.com/23463190/56460481-6f396f00-6371-11e9-9df0-07cbfd19e1de.png)

Let me know if you want anything from me. I'm pobably going to try 1.0.0 instead in the meantime.

**Comment by brianandcamera** [comment]
When using 1.0.0:

![image](https://user-images.githubusercontent.com/23463190/56461920-6738f980-6388-11e9-9ddf-8bd795b0425f.png)

**Comment by Zer0CoolX** [comment]
I am looking into your issue with running from git. Looks like that line regards a Maven command.

As for your stable attempt, that line is for LetsEncrypt. Most likely, it failed the challenge. I would need more info the from the log generated. If you have not setup your server to be accessible on 80/443 from the outside world and/or have not setup a public domain with the proper DNS settings to point to that machine's public IP than certbot will fail. IE: its possible/likely the stable 1.0.0. attempt failed because of settings external to the script or incorrect entries for the Lets Encrypt parameters. The log would tell me more.

**Comment by Zer0CoolX** [comment]
I have committed a change to fix the issue you had installing from Git. Versions of the script with build dates from 4/22/2019 on contain the fix.

I await to hear back from you regarding the attempt using Lets Encrypt. Please give me as much details as you can regarding it and I will try and help.
