### ISSUE TITLE
[BUG] Script fails when trying to restart Nginx

### ISSUE THREAD

**Issue by ccmks** [Zer0CoolX/guacamole-install-rhel#50]
Hello

I ran your script on freshly installed Centos 7. But keep getting the ngix error despite of re-installing the Centos again from scratch. Please advise.

Thank you

![image](https://user-images.githubusercontent.com/49300986/56642637-77afe380-66aa-11e9-9717-75339ebb439f.png)

**Comment by Zer0CoolX** [comment]
The line that is failing is simply trying restart nginx and Nginx is failing to start. This could be due to configuration options you selected for Nginx. Please check the log file produced by the script and see if it provides any information about Nginx having other issues (installing, configuring, etc.). Worst case send me/post the log file (removing any personally identifiable content first).

Also please provide the information requested by the template for this type of issue. What options did you select, what values did you provide the prompts, etc.

I am testing the script again to ensure this isnt an issue with Nginx source itself. With more info I may be able to help you.

**Comment by Zer0CoolX** [comment]
After review, it looks like Nginx changed the behavior of how it reads and validates the configuration files. I am looking into this and will post a fix as soon as I work one out. Thanks

**Comment by Zer0CoolX** [comment]
I have committed changes to the script to resolve the problem. Please re-download the script and try it again. Post back and verify if it worked for you. I will leave this issue open for ~7 days from now to ensure others see it and to give you time to reply back.

Thanks

**Comment by StumblingFelix** [comment]
Same issue for me on fresh Centos 7 VM.  I ran the updated script.


Nginx Configurations

-Making Nginx config backup...

-Generate Nginx guacamole.config...

-Generate Nginx guacamole_ssl.config...

-Enable & Start Nginx Service...
Created symlink from /etc/systemd/system/multi-user.target.wants/nginx.service to /usr/lib/systemd/system/nginx.service.


Setting SELinux Context...
setsebool:  SELinux is disabled.


%%% ERROR (Script Failed) | Line 1579 | command: setsebool -P httpd_can_network_connect 1 | exit code: 1 %%%

**Comment by StumblingFelix** [comment]
I has having the same issue as ccmks on a fresh Centos 7 install.  Your script update resolved the problem.  The only thing I had to do was change SELinux from disabled to permissive with the new script.

Thank you for making our jobs easier with this great script!

**Comment by ccmks** [comment]
I think the script fixed the NGIX but now I got different issue

![image](https://user-images.githubusercontent.com/49300986/56720335-389a9480-6775-11e9-9298-b785889c9480.png)

**Comment by Zer0CoolX** [comment]
@StumblingFelix - Thanks for confirming the update resolved the Nginx issue. You should not have to turn SEL off in any fashion. The script should properly set all SEL context. If you wouldnt mind feel free to open another issue regarding SEL if you got any errors, logged anything, etc. regarding it.

@ccmks That error likely means it failed to generate the LetsEncrypt cert which could be due to your settings/selections. Please check your log generated by the script and let me know what it says about the Lets Encrypt output.

Also, as per my first comment:

> Also please provide the information requested by the template for this type of issue. What options did you select, what values did you provide the prompts, etc.

The more info I have the less questions I need to ask you to help you find a resolution. Of course omit any personal/sensitive information.

I will run another test myself to check that Lets Encrypt works for me, if it does then its very likely a settings issue. Verify you have ports 80/443 open on your router/hardware firewall and forwarded to your server. Make sure your public domain has properly been setup to point to your public IP address (A record and such). You may consider setting up a simple http site to verify you have configured the router/firewall and public domain up correctly prior to attempting to use the script. In the mean time I will let you know if I find any further bugs.

**Comment by Zer0CoolX** [comment]
@ccmks I just tested with LetsEncrypt and it worked without error. I am fairly confident that your issues have to do with either selections made for the prompts of the script causing LE to fail generating the cert or external settings like your router/hardware firewall (port forwarding, NAT, etc.), public domain setup (A record, DNS, etc.), etc.

With further information I can try and help you. I am going to start another issue specifically for that as it seems like the bug reported in the OP is fixed. I will mention your comment in the new issue with your reply about LE failing.

I am going to leave this issue open for a few days to give you time to follow the convo to the new issue. Thanks

**Comment by Zer0CoolX** [comment]
New [HELP] request opened on your behalf here https://github.com/Zer0CoolX/guacamole-install-rhel/issues/52#issue-437236557

Once you reply there I will close this thread (or if a few days pass with no response.
