### ISSUE TITLE
[REQ] cleanup option

### ISSUE THREAD

**Issue by chrnin** [Zer0CoolX/guacamole-install-rhel#71]
While installing guacamole I had some issues that prevented the script to go straight to the end, and I had to guess what things had to be deleted/cleaned to resume installation.

2 ideas with that:
- the ability to cleanup install and resume installation process from zero after the issue has been fixed by the user.
- an option to reuse the same options (maybe a resume file with options stored in it ?)

**Comment by Zer0CoolX** [comment]
I am sorry you ran into trouble.

While this sounds like a good idea, in ideal circumstances it would be, my initial thoughts on the matter are that this would be immensely complicated to implement assuming its even possible.

I would have to account, somehow, for every possible reason the script could have failed and then uniquely address each possible cause. All while keeping track of what steps in the script actually executed and which did not. Then lump on top of that optional things a specific user may have selected from the menus (LDAPS vs LDAP, Let's Encrypt vs self-signed cert, etc.).

On top of all that, I would have to keep track of the system prior to running the script to know what I can and cannot change, for Ex: if the server already had the firewall ports for HTTP and HTTPS open, I wouldn't want to close them just because the script failed as this could potentially cause other issues for that user.

I would imagine that such an effort would at a minimum double the current amount of code in the script (roughly 2k lines of code to 4k+). Then there is the matter of testing it to ensure it even works. It would be practically impossible for me to test every way in which the script could fail.

This is why I have went to the trouble of logging as much as possible and producing precise error messages as well as advising users to attempt using the script in a test environment to iron out issues prior to using in production.

The information provided via the log and/or error message should give enough info to resolve issues and understand why the script failed. Being able to quickly re-attempt the install is something I have, for now, left to the end user.

I highly recommend testing the script in a VM, with a snapshot taken before executing the script. This way, if it fails, all you need to do is restore the snapshot and try again. By doing so, you can more easily work out all of the possible issues with your unique install and environment that I cannot account for including your; network setup, server configuration, selected options from the script, manually entered parameters used by the script, etc.

I appreciate the recommendation and will keep it in mind, but for now I don't see it being feasible for me to do. I will leave this open for now to give you time to reply. Thanks

**Comment by chrnin** [comment]
No problem, I had no dream that it would go straight forward... I think I gained a lot of time thanks to your script, so I'm pretty happy with the result.

I did'nt thought it would be so complicated at first because I didn't have much trouble, for instance I just had to clean some files and drop the mariadb database and root mariadb password. Thanks for you answer ! :)
