### ISSUE TITLE
[REQ]  Several "enter the password" prompts shown in plain text on screen

### ISSUE THREAD

**Issue by riahc3** [Zer0CoolX/guacamole-install-rhel#77]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. You have read the wiki and followed its guidelines including requirements, troubleshooting, etc.? Y

**Details**
OS/Version: CentOS 7
Guacamole Source: Git

**Describe the bug**
When asked to enter the password on several prompts, when typing it on the screen, it shows it in non hidden plain text on screen. It should be either blanked like most Linux password prompts and/or masked out with symbols.

**Comment by Zer0CoolX** [comment]
Hello, Thank you for bringing this up.

This was something I had considered but was unsure how to accomplish. In the end, at the time, I decided not to pursue it for 2 reasons:

- The likelihood of someone other than the person who made the password seeing it was low. I could not come up with a viable "common" circumstance in which multiple people would be working together to run a single instance of the script.
- The script provides summary menu(s) from which the passwords can be reviewed anyhow. This is intentional.

So even if I made the password entries blank or obscured their entry, the individual running the script could still review the entries via the summary menus anyhow.

The only thing obscuring the entry may protect against is someone seeing the entry over ones shoulder, which would be a relatively small window of opportunity as each menu replaces the previous making the entered password visible for a couple of seconds or a minute.

However, if you know how to accomplish this or can point me to a resource that can help me do this I am open to ideas. If it does not drastically alter existing code or other functionality I would be happy to add a means of having the password entry obscured.

Thanks
