### ISSUE TITLE
[REQ] Minimal Custom Login Screen

### ISSUE THREAD

**Issue by wicknet** [Zer0CoolX/guacamole-install-rhel#91]
This project is BY FAR the most complete and useful automation of spinning up a new Guacamole server  on CentOS 7. Having tried multiple repos, including the official one, without success, it was wonderful to have a working remote access server complete with a Letsencrypt SSL cert in less than 10 minutes. 

Kudos on a superb job!

Your repo with a custom login extension for Guac has, unfortunately, been less easy to follow. All attempts to decrypt, modify and repack the "branding.jar" file (on Mac and Windows) and upload it have not met with success. It also took hours to search and test various strategies to unpack and pack the jar file. Also the "restorecon" command for setting context for SELinux failed during execution.

Wondering if it's easier (and even possible) in your script to leave the original login dialog box as is but somehow add a single line above it (through CSS?) specifying a Company Name that a user can input as a custom variable during script execution? 

Fingers crossed :)

**Comment by Zer0CoolX** [comment]
Thanks for the praise. I assume you are talking about my other project: https://github.com/Zer0CoolX/guacamole-customize-loginscreen-extension

I would recommend, if you have not already, reading the source of my inspiration for the project here: https://github.com/Zer0CoolX/guacamole-customize-loginscreen-extension/wiki/Helpful-Resources

Essentially I took the info from there and built a "template" .jar for people to customize as they like. I then wrote up directions to help others manually create their desired .jar.

It does however require an understanding of or the ability to lookup info about modifying/working with css and json.

As mentioned in that projects readme, I recommend using the dev tools of your browser on the stock login page of Guacamole to make changes (at least to the CSS) so the effects can be seen in real time and temporarily changed. Record the working modifications and then applying them in the .jar.

The whole point of using an extension to do this is to not change any code related to Guacamole as it would be over written by updates and could potentially cause other issues (as is explained in the readme and source forum posts).

So if I was to automate any portion of this and include it, it would/should be done using exactly the same approach, IE: I would just be automating the manual process of using the extension to customize the login page.

That may sound well and good to others, but it would be an immense amount of work for me in addition to what I already do. It would also be next to impossible for me to account for all the things people may want to customize and to ensure they do so properly without breaking anything.

This way people can customize it exactly as they like. Since they are doing it hands on, reversing it should they not like the outcome would be easy (vs having it done automated and not working, then people not knowing how to remove the extension).

Maybe in the future it can be something I would automate, but for now it is a separate project and unlike this script, is simply a template to give people a starting point and guidance for a manual process.

I would recommend downloading the jar, leaving it as is and running the script with it as is. If it works and the login screen is customized as per the template, then I would try altering the .jar in a simple way (change the text or the background color) and trying again. If the unchanged template doesn't work for you let me know and I can see if something has changed to cause this, but as far as I know its still valid (and I have customized versions used in production that work).

**Comment by wicknet** [comment]
Thank you for your detailed and thoughtful response re. the complexity in implementing the requested feature. Completely understandable.

I think my mistake was trying to upload the jar extension post installation. I'll try spinning up a new server with the script pointing to the unchanged jar file first and then make incremental changes in it if/when it works.

Thanks again.
